name: Build Snapshot Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Make repository name in lower case for docker upload
        id: repository-name-adjusted
        uses: ASzc/change-string-case-action@v3
        with:
          string: ${{ github.repository }}

      - name: Get version from github ref and sha
        id: get_version
        run: echo "version=${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Check version
        id: check_version
        run: echo ${{ steps.get_version.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm64, linux/arm
          build-args: VERSION=${{ steps.get_version.outputs.version }}
          push: true
          tags: |
            ghcr.io/${{ steps.repository-name-adjusted.outputs.lowercase }}/vehicleupdatemanager:SNAPSHOT
            ghcr.io/${{ steps.repository-name-adjusted.outputs.lowercase }}/vehicleupdatemanager:${{ steps.get_version.outputs.version }}
