name: Source Code Validation

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  code-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17.2'

    - name: Setup GO environment
      run: |
            go mod download
            go install golang.org/x/lint/golint@latest
            go get -t ./...
    - name: Fmt
      run: |
         unformatted_code=$(gofmt -l .)
         if [ -n "$unformatted_code" ]; then
           echo "Improperly formatted code:"
           echo "$unformatted_code"
           exit 1
         fi
    - name: Lint
      run: |
           golint -set_exit_status ./...
    - name: Vet
      run: |
            go vet ./...
    - name: Unit tests
      run: |
            go test ./... -coverprofile coverage.out -covermode count
            go tool cover -func coverage.out
    - name: Quality Gate
      env:
           TESTCOVERAGE_THRESHOLD: 60
      run: |
            percentCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Test coverage : $percentCoverage %"
            if (( $(echo "$percentCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
                echo "OK"
            else
                echo "Test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
                echo "Failed"
                exit 1
            fi
